<?php

namespace CatLab\Accounts\Enums;

/**
 * Class Errors
 * @package CatLab\Accounts\Enums
 */
class Errors
{
    const USERNAME_DUPLICATE = 'USERNAME_DUPLICATE';
    const PASSWORD_INVALID = 'PASSWORD_INVALID';
    const CONFIRM_PASSWORD_INVALID = 'PASSWORD_CONFIRMATION_INVALID';
    const PASSWORD_INCORRECT = 'PASSWORD_INCORRECT';
    const EMAIL_DUPLICATE = 'EMAIL_DUPLICATE';
    const USER_NOT_FOUND = 'USER_NOT_FOUND';
    const EMAIL_INVALID = 'EMAIL_INVALID';
    const USERNAME_INVALID = 'USERNAME_INVALID';
    const INVALID_REQUEST = 'INVALID_REQUEST';
    const BIRTHDATE_INVALID = 'BIRTHDATE_INVALID';
    const BIRTHDATE_AGE_GATE = 'BIRTHDATE_AGE_GATE';
    const PASSWORD_RECOVERY_ACTIVE_REQUEST = 'PASSWORD_RECOVERY_ACTIVE_REQUEST';
}
